<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_ecms_infoclass_soft`;");
E_C("CREATE TABLE `phome_ecms_infoclass_soft` (
  `classid` int(10) unsigned NOT NULL DEFAULT '0',
  `zz_title` text NOT NULL,
  `z_title` varchar(255) NOT NULL DEFAULT '',
  `qz_title` varchar(255) NOT NULL DEFAULT '',
  `save_title` varchar(10) NOT NULL DEFAULT '',
  `zz_titlepic` text NOT NULL,
  `z_titlepic` varchar(255) NOT NULL DEFAULT '',
  `qz_titlepic` varchar(255) NOT NULL DEFAULT '',
  `save_titlepic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstime` text NOT NULL,
  `z_newstime` varchar(255) NOT NULL DEFAULT '',
  `qz_newstime` varchar(255) NOT NULL DEFAULT '',
  `save_newstime` varchar(10) NOT NULL DEFAULT '',
  `zz_banben` text NOT NULL,
  `z_banben` varchar(255) NOT NULL,
  `qz_banben` varchar(255) NOT NULL,
  `save_banben` varchar(10) NOT NULL,
  `zz_daxiao` text NOT NULL,
  `z_daxiao` varchar(255) NOT NULL,
  `qz_daxiao` varchar(255) NOT NULL,
  `save_daxiao` varchar(10) NOT NULL,
  `zz_shouquan` text NOT NULL,
  `z_shouquan` varchar(255) NOT NULL,
  `qz_shouquan` varchar(255) NOT NULL,
  `save_shouquan` varchar(10) NOT NULL,
  `zz_pingtai` text NOT NULL,
  `z_pingtai` varchar(255) NOT NULL,
  `qz_pingtai` varchar(255) NOT NULL,
  `save_pingtai` varchar(10) NOT NULL,
  `zz_pingfen` text NOT NULL,
  `z_pingfen` varchar(255) NOT NULL,
  `qz_pingfen` varchar(255) NOT NULL,
  `save_pingfen` varchar(10) NOT NULL,
  `zz_guanwang` text NOT NULL,
  `z_guanwang` varchar(255) NOT NULL,
  `qz_guanwang` varchar(255) NOT NULL,
  `save_guanwang` varchar(10) NOT NULL,
  `zz_morepic` text NOT NULL,
  `z_morepic` varchar(255) NOT NULL,
  `qz_morepic` varchar(255) NOT NULL,
  `save_morepic` varchar(10) NOT NULL,
  `zz_rjjx` text NOT NULL,
  `z_rjjx` varchar(255) NOT NULL,
  `qz_rjjx` varchar(255) NOT NULL,
  `save_rjjx` varchar(10) NOT NULL,
  `zz_down` text NOT NULL,
  `z_down` varchar(255) NOT NULL,
  `qz_down` varchar(255) NOT NULL,
  `save_down` varchar(10) NOT NULL,
  `zz_bendidown` text NOT NULL,
  `z_bendidown` varchar(255) NOT NULL,
  `qz_bendidown` varchar(255) NOT NULL,
  `save_bendidown` varchar(10) NOT NULL,
  `zz_tishi` text NOT NULL,
  `z_tishi` varchar(255) NOT NULL,
  `qz_tishi` varchar(255) NOT NULL,
  `save_tishi` varchar(10) NOT NULL,
  `zz_ruanjianjieshao` text NOT NULL,
  `z_ruanjianjieshao` varchar(255) NOT NULL,
  `qz_ruanjianjieshao` varchar(255) NOT NULL,
  `save_ruanjianjieshao` varchar(10) NOT NULL,
  `zz_ftitle` text NOT NULL,
  `z_ftitle` varchar(255) NOT NULL,
  `qz_ftitle` varchar(255) NOT NULL,
  `save_ftitle` varchar(10) NOT NULL,
  `zz_newstext` text NOT NULL,
  `z_newstext` varchar(255) NOT NULL,
  `qz_newstext` varchar(255) NOT NULL,
  `save_newstext` varchar(10) NOT NULL,
  `zz_dianping` text NOT NULL,
  `z_dianping` varchar(255) NOT NULL,
  `qz_dianping` varchar(255) NOT NULL,
  `save_dianping` varchar(10) NOT NULL,
  `zz_yuyan` text NOT NULL,
  `z_yuyan` varchar(255) NOT NULL,
  `qz_yuyan` varchar(255) NOT NULL,
  `save_yuyan` varchar(10) NOT NULL,
  PRIMARY KEY (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=gbk");

@include("../../inc/footer.php");
?>