<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_ecms_infoclass_phone`;");
E_C("CREATE TABLE `phome_ecms_infoclass_phone` (
  `classid` int(10) unsigned NOT NULL DEFAULT '0',
  `zz_title` text NOT NULL,
  `z_title` varchar(255) NOT NULL DEFAULT '',
  `qz_title` varchar(255) NOT NULL DEFAULT '',
  `save_title` varchar(10) NOT NULL DEFAULT '',
  `zz_titlepic` text NOT NULL,
  `z_titlepic` varchar(255) NOT NULL DEFAULT '',
  `qz_titlepic` varchar(255) NOT NULL DEFAULT '',
  `save_titlepic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstime` text NOT NULL,
  `z_newstime` varchar(255) NOT NULL DEFAULT '',
  `qz_newstime` varchar(255) NOT NULL DEFAULT '',
  `save_newstime` varchar(10) NOT NULL DEFAULT '',
  `zz_banben` text NOT NULL,
  `z_banben` varchar(255) NOT NULL,
  `qz_banben` varchar(255) NOT NULL,
  `save_banben` varchar(10) NOT NULL,
  `zz_daxiao` text NOT NULL,
  `z_daxiao` varchar(255) NOT NULL,
  `qz_daxiao` varchar(255) NOT NULL,
  `save_daxiao` varchar(10) NOT NULL,
  `zz_shouquan` text NOT NULL,
  `z_shouquan` varchar(255) NOT NULL,
  `qz_shouquan` varchar(255) NOT NULL,
  `save_shouquan` varchar(10) NOT NULL,
  `zz_pingfen` text NOT NULL,
  `z_pingfen` varchar(255) NOT NULL,
  `qz_pingfen` varchar(255) NOT NULL,
  `save_pingfen` varchar(10) NOT NULL,
  `zz_morepic` text NOT NULL,
  `z_morepic` varchar(255) NOT NULL,
  `qz_morepic` varchar(255) NOT NULL,
  `save_morepic` varchar(10) NOT NULL,
  `zz_rjjx` text NOT NULL,
  `z_rjjx` varchar(255) NOT NULL,
  `qz_rjjx` varchar(255) NOT NULL,
  `save_rjjx` varchar(10) NOT NULL,
  `zz_down` text NOT NULL,
  `z_down` varchar(255) NOT NULL,
  `qz_down` varchar(255) NOT NULL,
  `save_down` varchar(10) NOT NULL,
  `zz_bendidown` text NOT NULL,
  `z_bendidown` varchar(255) NOT NULL,
  `qz_bendidown` varchar(255) NOT NULL,
  `save_bendidown` varchar(10) NOT NULL,
  `zz_ftitle` text NOT NULL,
  `z_ftitle` varchar(255) NOT NULL,
  `qz_ftitle` varchar(255) NOT NULL,
  `save_ftitle` varchar(10) NOT NULL,
  `zz_newstext` text NOT NULL,
  `z_newstext` varchar(255) NOT NULL,
  `qz_newstext` varchar(255) NOT NULL,
  `save_newstext` varchar(10) NOT NULL,
  `zz_dianping` text NOT NULL,
  `z_dianping` varchar(255) NOT NULL,
  `qz_dianping` varchar(255) NOT NULL,
  `save_dianping` varchar(10) NOT NULL,
  `zz_itunes` text NOT NULL,
  `z_itunes` varchar(255) NOT NULL,
  `qz_itunes` varchar(255) NOT NULL,
  `save_itunes` varchar(10) NOT NULL,
  `zz_iosyy` text NOT NULL,
  `z_iosyy` varchar(255) NOT NULL,
  `qz_iosyy` varchar(255) NOT NULL,
  `save_iosyy` varchar(10) NOT NULL,
  `zz_iosyybendi` text NOT NULL,
  `z_iosyybendi` varchar(255) NOT NULL,
  `qz_iosyybendi` varchar(255) NOT NULL,
  `save_iosyybendi` varchar(10) NOT NULL,
  `zz_pcdown` text NOT NULL,
  `z_pcdown` varchar(255) NOT NULL,
  `qz_pcdown` varchar(255) NOT NULL,
  `save_pcdown` varchar(10) NOT NULL,
  `zz_diggtop` text NOT NULL,
  `z_diggtop` varchar(255) NOT NULL,
  `qz_diggtop` varchar(255) NOT NULL,
  `save_diggtop` varchar(10) NOT NULL,
  `zz_diggdown` text NOT NULL,
  `z_diggdown` varchar(255) NOT NULL,
  `qz_diggdown` varchar(255) NOT NULL,
  `save_diggdown` varchar(10) NOT NULL,
  `zz_yxlx` text NOT NULL,
  `z_yxlx` varchar(255) NOT NULL,
  `qz_yxlx` varchar(255) NOT NULL,
  `save_yxlx` varchar(10) NOT NULL,
  PRIMARY KEY (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=gbk");

@include("../../inc/footer.php");
?>